display_name: LongyunVPN

packager: Sakawat Hossain
packagerEmail: sakawathossain2000@gmail.com
license: GPL-3.0

priority: optional
section: x11
installed_size: 6604
essential: false
icon: ./assets/images/icon.png

keywords:
  - LongyunVPN
  - Clash
  - ClashMeta
  - Proxy

generic_name: LongyunVPN

group: Applications/Internet

startup_notify: true