display_name: LongyunVPN

icon: ./assets/images/icon.png

keywords:
  - LongyunVPN
  - Clash
  - ClashMeta
  - Proxy

generic_name: LongyunVPN

categories:
  - Network

startup_notify: true

include: []