script_template: inno_setup.iss
app_id: 9399FBAE-4986-4943-BBAA-E16D46DE2BEE
app_name: LongyunVPN
publisher: LongyunVPN
publisher_url: https://github.com/Sakawat-hossain/LongyunVPN
display_name: LongyunVPN
executable_name: LongyunVPN.exe
output_base_file_name: LongyunVPN-Setup.exe
setup_icon_file: ..\windows\runner\resources\app_icon.ico
locales:
  - lang: zh
    file: ..\windows\packaging\exe\ChineseSimplified.isl
  - lang: en
privileges_required: admin
